# Custom RAGAS -style metric: DecompositionQuality
# To evaluate whether a query decomposer breaks complex queries 
# into retrievable sub-queries (good) vs synthesis queries (bad)

from typing import List, Literal
from ragas.llms import llm_factory
from openai import AsyncOpenAI
import json
import asyncio
from dotenv import load_dotenv

from pydantic import BaseModel, Field

class SubQueryAnalysis(BaseModel):
    """
    Analysis of a single sub-query
    """
    query: str = Field(description='The sub-query being analyzed')
    type: Literal['retrievable', 'synthesis'] = Field(description='Whether this is retrievable or requires synthesis')
    reason: str = Field(description='Brief explanation of the classification')

class DecompositionQualityOutput(BaseModel):
    """
    Structured output for decomposition quality evaluation
    """
    per_query: List[SubQueryAnalysis] = Field(description='Analysis of each sub-query')
    score: float = Field(ge=0.0, le=1.0, description='Overall quality score from 0.0 to 1.0')
    reasoning: str = Field(description='Overall assessment of decomposition quality')

class DecompositionQuality:
    def __init__(self, llm):
        self.llm = llm

    def score(self, original_query: str, sub_queries: List[str]) -> dict:
        """
        Score Decomposition Quality.

        input:
        original_query: str - the original query for the retriever before decomposition
        sub_queries: List[str] - list of subqueries generated by the decomposer

        Returns: dict
        {
            'score': float(0.0 to 1.0),
            'reason': str,
            'per_query_analysis': list
        }
        """

        # Building a prompt to the llm
        prompt = self._build_prompt(original_query, sub_queries)

        # LLM Call (synchronous wrapper around async)
        result = asyncio.run(self._evaluate_async(prompt))

        return result

    def _build_prompt(self, original_query: str, sub_queries: List[str]) -> str:
        """
        Build the evaluation prompt for the llm
        """

        sub_q_formatted = "\n".join([f"{i+1}. {q}" for i, q in enumerate(sub_queries)])

        prompt = f"""
        You are evaluating the quality of query decomposition for a multi-hop retrieval system.

        **Original Query:**
        {original_query}

        **Decomposed Sub-Questions:**
        {sub_q_formatted}

        **Task:**
        For each sub-question, determine if it is:
        - RETRIEVABLE: Can be answered by finding facts in documents (names, dates, statements, events)
        - SYNTHESIS: Requires comparing, judging, or synthesizing information across sources

        Then provide:
        1. Per-question analysis (retrievable or synthesis + brief reason)
        2. Overall score from 0.0 to 1.0:
        - 1.0 = All sub-questions are retrievable facts
        - 0.5-0.8 = Mix of retrievable and synthesis
        - 0.0-0.4 = Most require synthesis

        Return ONLY valid JSON in this exact format:
        {{
        "per_question": [
            {{"question": "...", "type": "retrievable|synthesis", "reason": "..."}},
            ...
        ],
        "score": 0.X,
        "reasoning": "Overall assessment of decomposition quality"
        }}
        """

        return prompt
    
    async def _evaluate_async(self, prompt: str) -> dict:
        """
        LLM call - and parse the response
        """

        # Resonse from llm generated
        result = await self.llm.agenerate(prompt, DecompositionQualityOutput)
        
        return {
            'score': result.score,
            'reasoning': result.reasoning,
            'per_query_analysis': [
                {
                    'query': item.query,
                    'type': item.type,
                    'reason': item.reason
                }
                for item in result.per_query
            ]
        }


def test_metric():
    """
    Testing the metric on one of the trace examples
    """

    load_dotenv()

    llm = llm_factory('gpt-4o-mini', client=AsyncOpenAI())
    metric = DecompositionQuality(llm)

    original_query = "Did the portrayal of Sam Bankman-Fried's financial actions remain the same in the TechCrunch " \
    "report on his intentions with his wealth published on October 2, 2023, and the TechCrunch report on the allegations " \
    "against him published on October 7, 2023?"

    sub_queries = [
        "What does the CNBC article say about Sam Bankman-Fried's approach to the composition of FTX's board?",
        "What does the TechCrunch article report about Sam Bankman-Fried's actions regarding the misuse of customer funds?",
        "How did the portrayal of Sam Bankman-Fried's financial actions differ between the two TechCrunch reports?"
    ]

    result = metric.score(original_query, sub_queries)

    print("="*70)
    print("DECOMPOSITION QUALITY TEST")
    print("="*70)
    print(f"\nOriginal Query: {original_query[:120]}...")
    print(f"\nSub-questions:")
    
    for i, sq in enumerate(sub_queries, 1):
        print(f"  {i}. {sq}")
    
    print(f"\n{'-'*70}")
    print(f"Score: {result['score']:.2f}")
    print(f"Reasoning: {result['reasoning']}")
    print(f"\nPer-Question Analysis:")

    for item in result['per_query_analysis']:
        print(f"  - {item['query'][:80]}...")
        print(f"    Type: {item['type']}, Reason: {item['reason']}")


if __name__=='__main__':
    test_metric()

